######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 7 13:36:16 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . res src
INCLUDEPATH += . src

# Input
HEADERS += src/MainWindow.h
FORMS += res/MainWindow.ui
SOURCES += src/main.cpp src/MainWindow.cpp
